In [18]:
#import sys
#!{sys.executable} -m pip install -r requirements.txt
import pandas as pd
import numpy as np
from numpy.linalg import matrix_power
%matplotlib inline
import matplotlib.pyplot as plt
from scipy.stats import uniform
from scipy.stats import expon
from scipy.stats import norm
from random import random

In [61]:
# Create transition matrix
P = np.array([[0.4, 0.6, 0.0],
              [0.4, 0.3, 0.3],
              [0.7, 0.0, 0.3]])
steady_P = P

# Create state space 
states = ['State 0', 'State 1', 'State 2']

exp_vals = [1, 2, 3, 4, 5, 6]
# Compute P^n for n in {2, 4, 8, 16, 32, 64}
for exp in exp_vals:
    power = 2 ** exp
    steady_P = np.linalg.matrix_power(P, power)
    print('Step ', str(exp), ': P^', str(power), sep = '')
    print(steady_P, end = '\n\n')

Step 1: P^2
[[0.4  0.42 0.18]
 [0.49 0.33 0.18]
 [0.49 0.42 0.09]]

Step 2: P^4
[[0.454  0.3822 0.1638]
 [0.4459 0.3903 0.1638]
 [0.4459 0.3822 0.1719]]

Step 3: P^8
[[0.4495774  0.38529582 0.16512678]
 [0.44951179 0.38536143 0.16512678]
 [0.44951179 0.38529582 0.16519239]]

Step 4: P^16
[[0.44954129 0.3853211  0.16513761]
 [0.44954128 0.3853211  0.16513761]
 [0.44954128 0.3853211  0.16513762]]

Step 5: P^32
[[0.44954128 0.3853211  0.16513761]
 [0.44954128 0.3853211  0.16513761]
 [0.44954128 0.3853211  0.16513761]]

Step 6: P^64
[[0.44954128 0.3853211  0.16513761]
 [0.44954128 0.3853211  0.16513761]
 [0.44954128 0.3853211  0.16513761]]



In [64]:
# Simulate Markov chain
def run_simulation(init_state, num_steps):
    curr_state = init_state
    state_list = [curr_state]
    state_1_count = 0
    link_count = 0
    for i in range(0, num_steps):
        # Get state number
        j = int(curr_state[-1])
        # Get corresponding row of transition matrix
        prob_vector = P[j]
        # Draw next state
        next_state = np.random.choice(states, replace = True, p = prob_vector)
        # Increment counters (if necessary)
        if curr_state == "State 1":
            state_1_count = state_1_count + 1
            if next_state == "State 2":
                link_count = link_count + 1
        state_list.append(next_state)
        curr_state = next_state
    # return list of all visited states, num. of times state 1 was visited, 
    # and num. of times transition 1 -> 2 was used       
    return state_list, state_1_count, link_count

steps = 100000
init_state = np.random.choice(states, replace = True)
state_list, state_count, link_count = run_simulation(init_state, steps)
# Get steady-state probability of state 1
pi_1 = steady_P[0][0]
# Get probability of 1 -> 2
p12 = P[0][1]

print("Number of times state 1 was visited in", steps, "steps:", state_count, end = "\n\n")
print("Number of times state 1 would be visited in", steps, "steps if initial distribution were steady:", round(pi_1 * steps), end = "\n\n")
print("Number of times link 1 -> 2 was used in", steps, "steps:", link_count, end = "\n\n")
print("Number of times link 1 -> 2 would be used in", steps, "steps if initial distribution were steady:", round(pi_1 * p12 * steps), end = "\n\n")

Number of times state 1 was visited in 100000 steps: 38525

Number of times state 1 would be visited in 100000 steps if initial distribution were steady: 44954

Number of times link 1 -> 2 was used in 100000 steps: 11475

Number of times link 1 -> 2 would be used in 100000 steps if initial distribution were steady: 26972

